name: Deploy Demo Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Add these permissions
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'

    - name: Install Root Dependencies
      run: yarn install

    - name: Install Demo Dependencies
      run: |
        cd demo
        yarn install

    - name: Build
      run: |
        cd demo
        yarn build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./demo
        enable_jekyll: false 